### ISSUE TITLE
Please add ShibGreen

### ISSUE THREAD

**Issue by prodchia** [gilnobrega/farmr#148]
{
    "Binary Name": "SHIBGreen",
    "Currency Symbol": "XShib",
    "Minor Currency Symbol": "byte",
    "Major to Minor Multiplier": 1e3,
    "Net": "mainnet",

    "Block Rewards": 100000.0,
    "Blocks Per 10 Minutes": 32.0,
    
    "Online Config": true,

    "Ports": {
        "harvester": 18785,
        "farmer": 18989,
        "fullNode": 18793,
        "wallet": 19587,
        "daemon": 44428
      }
    
}

**Comment by gilnobrega** [comment]
XShib was added in v1.7.7
https://github.com/gilnobrega/farmr/releases/tag/v1.7.7.3
