### ISSUE TITLE
Notifications stopped???? 

### ISSUE THREAD

**Issue by Adya84** [gilnobrega/farmr#149]
All of a sudden my notifications arnt coming through for new blocks???

Anyone got a fix or where I should try fix this, I've reinstalled it setup again and all working fine just doesn't send notification emails now???

Used to say online or offline aswell.

**Comment by ByronAP** [comment]
no emails here either

**Comment by gilnobrega** [comment]
farmr's email is rate limited at this moment, please use the discord login if you want notifications through the discord bot.

**Comment by gilnobrega** [comment]
Email notifications are working again
