### ISSUE TITLE
Forks: Support AedgeCoin

### ISSUE THREAD

**Issue by rymdluo** [gilnobrega/farmr#151]
Hi, I am the project owner of AedgeCoin and would like to see about adding support for it on farmr.

Here are some details about the project:

Launched: 2021-10-17
Name of coin/Ticker Symbol: Aedge/AEC
Website: aedgecoin.com
ChiaForum Thread: https://chiaforum.com/t/aedgecoin-is-a-chiafork-with-a-focus-on-algotrading/14250
Newsletter: http://newsletter.aedgecoin.com/
Github: https://github.com/AedgeCoin/aedge-blockchain

**Comment by jpmath54** [comment]
Works for me:
`{
    "Binary Name": "aedge",
    "Folder Name": ".aedge",
    "Currency Symbol": "aec",
    "Minor Currency Symbol": "mojo",
    "Net": "mainnet",
    
    "Block Rewards": 2.0,
    "Blocks Per 10 Minutes": 32.0,
    
    "Online Config": true,
    
    "Ports": {
        "harvester": 9072,
        "farmer": 9071,
        "fullNode": 9067,
        "wallet": 9768,
        "daemon": 55912
      }
}`

**Comment by gilnobrega** [comment]
Aec was added in v1.7.7
https://github.com/gilnobrega/farmr/releases/tag/v1.7.7.3

Thank you for your contribution :)
