### ISSUE TITLE
Is farmr down?

### ISSUE THREAD

**Issue by prodchia** [gilnobrega/farmr#154]
I am not able to login on farmr.net portal using discord

**Comment by gilnobrega** [comment]
Yes, the server is currently offline. I don't know why but the VPS is unreachable. Will try to fix it later tonight (GMT)

**Comment by JerkyChew899** [comment]
Anything we can do to help? Looks to still be down.

**Comment by tutorialevideo** [comment]
still down!

**Comment by gilnobrega** [comment]
Everything should be back online. Please let me know if something is not working.

**Comment by gilnobrega** [comment]
> Is there something I need to do to re-synch everything?
> 
> 

Yes. Unfortunately it was not possible to backup the previous database, so the server doesn't know which devices belong to you.

This gets fixed if you re-link all devices.
