### ISSUE TITLE
Sit says can't find harvester or farming 

### ISSUE THREAD

**Issue by Adya84** [gilnobrega/farmr#165]
When farmr is started after I've done some updates and fixes to guis, I now get a message from farmr saying can't find running harvester or farming when this is open and farming. This makes it not go any further and will not open at all. 

Does anyone know what I need to do too fix this issue not sure what's causing it rest open fine if I removes sit file???

**Comment by gilnobrega** [comment]
Newer versions of sit should use this template file:
https://github.com/gilnobrega/farmr/blob/8b5eee566008d5eeaecfcbb3f0c50b6b61f7d8e2/blockchain/sit.json.template
While older versions use different RPC ports:
https://github.com/gilnobrega/farmr/blob/b0871404c3fc7b68a2e42ce71a0e8c566d39dd77/blockchain/sit.json.template

Try both and let me know if any of them work

**Comment by Adya84** [comment]
It's used to work, nothing has changed version wise. I just had to
uninstall sit and reinstall now doesn't work.

Get black screen with harvester can't be found not farming

**Comment by gilnobrega** [comment]
Yes, sit updated their ports recently, you need to replace sit.json with the contents of this file
 https://github.com/gilnobrega/farmr/blob/8b5eee566008d5eeaecfcbb3f0c50b6b61f7d8e2/blockchain/sit.json.template

**Comment by Adya84** [comment]
They updated them weeks ago I was using farm r yesterday the ports are the
same

**Comment by Adya84** [comment]
Shit u was right it's fixed it top guy thnaks ever so much, just double
checked and was all 11 not 22 :)
