### ISSUE TITLE
v.1.8.0.0 farmr-windows-x64.zip - farmr.exe and hpool.exe are the same file?

### ISSUE THREAD

**Issue by jpmath54** [gilnobrega/farmr#167]
At least that's what meld reports! ;-)

**Comment by gilnobrega** [comment]
That makes sense, hpool.exe is simply farmr.exe with ``hpool`` as argument, e.g.: ``farmr.exe hpool``

**Comment by jpmath54** [comment]
OK! My mistake, you can close!
